cache:
  apt: true
  directories:
    - node_modules

git:
  depth: 1

branches:
  only:
    - master
    - develop

language: node_js

node_js:
  - "6"
  - "6.9.1"

before_install:
  - t=4.0.5 && v=`npm -v` && x=`printf "$v\n$t" | sort -V | head -n 1` && [ $x != $t ] && npm install -g npm || echo "no need to upgrade npm."

install:
  - npm install

script:
  - npm run ci
